Repository jornadayu/yu-open-lib, pull requests merged in 2022-04, with the labels that each got.

#27 [YURI-2756] Corrigir problema 'out of memory' ao fazer build/deploy do Storybook
  .github/workflows/storybook_build.yml
  .github/workflows/storybook_deploy.yml
Labels: bug

#28 Corrigir uso de React Fragments nao-suportados e adicionar eslint rule pra auto-corrigir
  .eslintrc
  .github/workflows/linting.yml
  .github/workflows/new_release.yml
  src/components/inputs/ImageDragAndDrop.tsx
  src/stories/dialogs/BaseDialog.stories.tsx
  src/stories/dialogs/ConfirmDialog.stories.tsx
  src/stories/dialogs/DialogTitle.stories.tsx
  src/stories/loaders/BackdropLoading.stories.tsx
  src/stories/loaders/LoadingLine.stories.tsx
  tsconfig.json
Labels: bug

#29 Adicionar configuracao de usuario do git pos-checkout em pipeline de release
  .github/workflows/new_release.yml
Labels: ci/cd

#30 [YURI-2821] Helper copyToClipboard e componente CopyableButton refatorados
  src/components/inputs/CopyableButton.tsx
  src/helpers/text.ts
  src/stories/inputs/CopyableButton.stories.tsx
Labels: enhancement

#31 [YURI-2820] Viewer de rich text
  src/components/RichTextViewer.tsx
  src/index.tsx
  src/stories/utils/RichTextViewer.stories.tsx
Labels: enhancement

#32 [YURI-2834] Bug ao tentar copiar textos com formato html mais de uma vez na página corrigido
  src/helpers/text.ts
Labels: bug

#33 Adicionar missing export de componente `BaseDialog`
  .storybook/preview.jsx
  src/index.tsx
  src/stories/dialogs/BaseDialog.stories.tsx
  src/stories/root/AppTheme.stories.mdx
  src/stories/root/Guidelines.stories.mdx
  src/stories/root/Intro.stories.mdx
  src/stories/root/V2Update.stories.mdx
Labels: bug

#34 [YURI-2879] Adicionar props de customização e legendas em componente 'EChartsFunnelGraph'
  src/components/graphs/EChartsFunnelGraph.tsx
  src/stories/graphs/EChartsFunnelGraph.stories.tsx
Labels: enhancement

#35 Atualizar Template de Changelog de releases para ter menos categorias
  .github/configs/changelog-builder.json
  src/components/graphs/EChartsFunnelGraph.tsx
Labels: documentation

#36 Corrigir tipagem de helper 'groupBy' e configurar unit tests
  .github/workflows/linting.yml
  package.json
  src/helpers/index.ts
  tests/groupBy.test.ts
  vitest.config.ts
  yarn.lock
Labels: bug

#37 [YURI-2901] Adicionar prop opcional 'allowEmptyValues' para EChartsFunnelGraph, pra permitir valores nulos no gráfico
  src/components/graphs/EChartsFunnelGraph.tsx
  src/stories/graphs/EChartsFunnelGraph.stories.tsx
Labels: enhancement

#38 Novo componente 'StatusChip'
  src/components/chips/StatusChip.tsx
  src/index.tsx
  src/stories/chips/StatusChip.stories.tsx
Labels: enhancement
